"""
plot_phase_diagram.py
====================

This script generates phase diagrams describing the feasibility region
of the ESS robust scheduling system.

A phase diagram classifies each hyperparameter configuration into one of
three system states:

    1. Computationally infeasible
       The optimization model could not be solved within the allowed
       time or size constraints.

    2. Operationally infeasible
       The model solved successfully, but simulation results indicate
       that the 95% service-level requirement is violated.

    3. Fully feasible
       The model solves successfully and satisfies the 95% service-level
       constraint in simulation.

The diagram visualizes how system feasibility changes as hyperparameters
vary, typically:

    x-axis : number of jobs (n_jobs)
    y-axis : robustness parameter (k) or variability level (sigma_scale)

Color legend:

    green   = fully feasible
    orange  = operationally infeasible
    red     = computationally infeasible
    gray    = missing / not simulated

Additional information printed in each cell includes:

    • probability of clearing the horizon
    • solver runtime (for computational failures)

This visualization helps identify:

    • system capacity limits
    • robustness parameter requirements
    • computational scalability limits

Input
-----
CSV generated by run_grid_search.py

Output
------
Phase diagrams saved to:

    results/figures/
"""
from __future__ import annotations

import argparse
from itertools import product
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
from matplotlib.colors import BoundaryNorm, ListedColormap


HYPERPARAM_COLS = ["n_jobs", "mu_scale", "sigma_scale", "k"]


def load_results(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)

    bool_cols = ["accepted_for_simulation", "meets_95_constraint", "system_ok"]
    for col in bool_cols:
        if col in df.columns and df[col].dtype != bool:
            mapped = (
                df[col]
                .astype(str)
                .str.strip()
                .str.lower()
                .map({"true": True, "false": False})
            )
            if mapped.notna().any():
                df[col] = mapped

    return df


def get_varying_hyperparams(df: pd.DataFrame) -> list[str]:
    varying = []
    for col in HYPERPARAM_COLS:
        if col in df.columns and df[col].nunique(dropna=True) > 1:
            varying.append(col)
    return varying


def choose_axes(varying_params: list[str]) -> tuple[str, str | None, list[str]]:
    if not varying_params:
        return "n_jobs", None, []

    x_col = "n_jobs" if "n_jobs" in varying_params else varying_params[0]
    remaining = [c for c in varying_params if c != x_col]

    if not remaining:
        return x_col, None, []

    y_col = remaining[0]
    facet_cols = remaining[1:]
    return x_col, y_col, facet_cols


def unique_sorted(series: pd.Series):
    return sorted(series.dropna().unique().tolist())


def iter_facet_slices(df: pd.DataFrame, facet_cols: list[str]):
    if not facet_cols:
        yield "all", df.copy()
        return

    value_lists = [unique_sorted(df[c]) for c in facet_cols]
    for combo in product(*value_lists):
        sub = df.copy()
        parts = []
        for c, v in zip(facet_cols, combo):
            sub = sub[np.isclose(sub[c], v)]
            parts.append(f"{c}-{v}")
        yield "__".join(parts), sub


def classify_case(row: pd.Series) -> int:
    """
    0 = computationally infeasible
    1 = operationally infeasible
    2 = fully feasible
    3 = missing / unknown
    """
    accepted = row.get("accepted_for_simulation", None)
    meets_95 = row.get("meets_95_constraint", None)

    if pd.isna(accepted):
        return 3
    if accepted is False:
        return 0
    if accepted is True and meets_95 is False:
        return 1
    if accepted is True and meets_95 is True:
        return 2
    return 3


def make_label(row: pd.Series) -> str:
    accepted = row.get("accepted_for_simulation", None)
    meets_95 = row.get("meets_95_constraint", None)
    prob_clear = row.get("prob_cleared_within_horizon", None)
    solve_time = row.get("solve_time_sec", None)

    if pd.isna(accepted):
        return "NA"

    if accepted is False:
        return f"{solve_time:.0f}s" if pd.notna(solve_time) else "Comp"

    if accepted is True and meets_95 is False:
        return f"{100 * prob_clear:.0f}%" if pd.notna(prob_clear) else "Op"

    if accepted is True and meets_95 is True:
        return "OK"

    return "NA"


def build_phase_tables(df: pd.DataFrame, x_col: str, y_col: str):
    tmp = df.copy()
    tmp["phase_class"] = tmp.apply(classify_case, axis=1)
    tmp["phase_label"] = tmp.apply(make_label, axis=1)

    phase_df = tmp.pivot_table(
        index=y_col,
        columns=x_col,
        values="phase_class",
        aggfunc="first",
    ).sort_index().sort_index(axis=1)

    label_df = tmp.pivot_table(
        index=y_col,
        columns=x_col,
        values="phase_label",
        aggfunc="first",
    ).sort_index().sort_index(axis=1)

    return phase_df, label_df


def sanitize_name(name: str) -> str:
    return (
        name.replace(" ", "_")
        .replace("/", "-")
        .replace("=", "-")
        .replace(",", "_")
        .replace(".", "p")
    )


def build_summary_text(df_slice: pd.DataFrame) -> str:
    lines = []

    def add_line(label, col, fmt="{:.1f}"):
        if col in df_slice.columns:
            val = df_slice[col].dropna()
            if len(val) > 0:
                lines.append(f"{label}: {fmt.format(val.mean())}")

    add_line("avg nominal job time", "mu_total_mean")
    add_line("avg combined sigma", "sigma_total_mean")
    add_line("avg k-buffer / job", "k_buffer_mean")
    add_line("avg robust job time", "p_robust_mean")
    add_line("avg nominal load / day", "avg_nominal_load_per_day")
    add_line("avg robust load / day", "avg_robust_load_per_day")
    add_line("avg total overtime", "avg_total_overtime")
    add_line("avg clear prob", "prob_cleared_within_horizon", "{:.2f}")

    return "\n".join(lines)


def plot_phase_for_slice(
    df_slice: pd.DataFrame,
    x_col: str,
    y_col: str,
    slice_name: str,
    csv_stem: str,
    out_dir: Path,
):
    phase_df, label_df = build_phase_tables(df_slice, x_col, y_col)
    if phase_df.empty:
        return

    values = phase_df.values

    cmap = ListedColormap([
        "#d73027",  # red = computationally infeasible
        "#fdae61",  # orange = operationally infeasible
        "#1a9850",  # green = feasible
        "#d9d9d9",  # gray = missing
    ])
    norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5, 3.5], cmap.N)

    fig = plt.figure(figsize=(12, 6))
    gs = fig.add_gridspec(1, 2, width_ratios=[3.5, 1.2], wspace=0.25)

    ax = fig.add_subplot(gs[0, 0])
    ax_info = fig.add_subplot(gs[0, 1])
    ax_info.axis("off")

    ax.imshow(values, cmap=cmap, norm=norm, aspect="auto")

    ax.set_xticks(np.arange(len(phase_df.columns)))
    ax.set_yticks(np.arange(len(phase_df.index)))
    ax.set_xticklabels(phase_df.columns)
    ax.set_yticklabels([f"{v:.2f}" if isinstance(v, float) else str(v) for v in phase_df.index])

    ax.set_xlabel(x_col)
    ax.set_ylabel(y_col)
    ax.set_title(f"System Phase Diagram | slice: {slice_name}", fontsize=13, pad=10)

    ax.set_xticks(np.arange(-0.5, len(phase_df.columns), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(phase_df.index), 1), minor=True)
    ax.grid(which="minor", color="white", linestyle="-", linewidth=1.6)
    ax.tick_params(which="minor", bottom=False, left=False)

    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            txt = label_df.iloc[i, j]
            if pd.notna(txt):
                ax.text(j, i, txt, ha="center", va="center", fontsize=9, color="black")

    legend_handles = [
        mpatches.Patch(color="#1a9850", label="Feasible"),
        mpatches.Patch(color="#fdae61", label="Operationally Infeasible"),
        mpatches.Patch(color="#d73027", label="Computationally Infeasible"),
        mpatches.Patch(color="#d9d9d9", label="Missing / Not Simulated"),
    ]
    ax.legend(
        handles=legend_handles,
        loc="upper left",
        bbox_to_anchor=(1.02, 1.0),
        frameon=True,
        title="Phase"
    )

    summary_text = build_summary_text(df_slice)
    ax_info.text(
        -0.36, 0.6,
        f"CSV: {csv_stem}\n\nSlice: {slice_name}\n\n{summary_text}",
        va="top",
        fontsize=10,
        family="monospace"
    )

    fig.suptitle("Automatic Phase Diagram", fontsize=15, y=1.02)
    plt.tight_layout()

    out_path = out_dir / f"phase_diagram_{sanitize_name(csv_stem)}__{sanitize_name(slice_name)}.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Automatically generate phase diagrams for all hyperparameter slices."
    )
    parser.add_argument(
        "--csv",
        type=str,
        default="results/grid_search/grid_search_results.csv",
        help="Path to grid search CSV."
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="results/figures",
        help="Directory to save figures."
    )
    parser.add_argument(
        "--x-col",
        type=str,
        default=None,
        help="Optional manual x-axis hyperparameter."
    )
    parser.add_argument(
        "--y-col",
        type=str,
        default=None,
        help="Optional manual y-axis hyperparameter."
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = load_results(str(csv_path))
    varying = get_varying_hyperparams(df)

    auto_x, auto_y, auto_facets = choose_axes(varying)
    x_col = args.x_col if args.x_col else auto_x
    y_col = args.y_col if args.y_col else auto_y

    if y_col is None:
        raise ValueError(
            "Not enough varying hyperparameters to make a 2D phase diagram. "
            "At least two hyperparameters must vary."
        )

    facet_cols = [c for c in varying if c not in [x_col, y_col]]

    print("Detected varying hyperparameters:", varying)
    print(f"Using x = {x_col}, y = {y_col}, facets = {facet_cols}")

    csv_stem = csv_path.stem

    for slice_name, df_slice in iter_facet_slices(df, facet_cols):
        if df_slice.empty:
            continue
        plot_phase_for_slice(
            df_slice=df_slice,
            x_col=x_col,
            y_col=y_col,
            slice_name=slice_name,
            csv_stem=csv_stem,
            out_dir=out_dir,
        )


if __name__ == "__main__":
    main()